In [ ]:
import pandas as pd
df = pd.read_excel("Students_Data.xlsx",sheet_name=0)

# Look at the Data:
df.head() # By Default head() gives first 5 rows. 
df.tail() # tail() gives last 5 rows by default.
df.sample(5)

       Name  Age       Department
2  Iftikhar   20       Civil Engr
4  Ali Khan   19    Architecture
5    Aizaz    21      Electronics
3  Abdullah   21               CS
1   Mushtaq   20  Electrical Engr

In [ ]:
# Understand the structure
df.shape # shape--> Check the size of Data (rows,column)
df.shape[0] # Get only rows
df.shape[1] # Get only columns
df.columns
df.index
df.size

3

In [ ]:
# Understand data types
df.info() # Get Complete Information
df.dtypes
len(df) # Returns the total number of Rows

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Age         6 non-null      int64
 2   Department  6 non-null      str
dtypes: int64(1), str(2)
memory usage: 276.0 bytes

6

In [ ]:
# Check missing data
df.isnull.sum().sum()
df.isnull().sum() # isnull() is used to Check missing values sum() is used to give total missing values
df.count() # --> Count Non-Missing Values

Name          0
Age           0
Department    0
dtype: int64

In [ ]:
df.notnull().sum() # Check for Non-Missing Values then counting them
df.describe() #--> Statistical Summary: i.e count, mean, std, min.. etc
df.dtypes #--> Check Data Types

             Age
count   6.000000
mean   20.000000
std     0.894427
min    19.000000
25%    19.250000
50%    20.000000
75%    20.750000
max    21.000000

In [82]:
# Working with Columns

df.columns #columns--> Get column Names
df.columns.tolist() # tolist--> To convert column names into a normal Python list
df["Name"] # View one column 
df.Name # We can also use this (Same Result)
df[["Name", "Age"]] # --> View Multiple Columns
df["Name"].unique() # Check Unique values in particular column

<StringArray>
['Faizan', 'Mushtaq', 'Iftikhar', 'Abdullah', 'Ali Khan', 'Aizaz ']
Length: 6, dtype: str

In [79]:
# Working with rows

df.duplicated() #--> Check for Duplicate Rows (dtype: Bool)
df[df.duplicated()] # See Duplicate Rows
df.iloc[2] # Select Specific Row
df.loc[0:5, ["Name", "Age"]] # Select Rows and Columns 
df.sample(5) # Show Random Rows

       Name  Age       Department
4  Ali Khan   19    Architecture
3  Abdullah   21               CS
2  Iftikhar   20       Civil Engr
1   Mushtaq   20  Electrical Engr
0    Faizan   19               CS

In [ ]:
# Statistics 

df["Age"].min() #--> Find Minimum Value.
df["Age"].max() #--> Find Maximum Value.
df["Age"].mean() # Calculate Average.
df["Age"].median() # Calculate Median.
df["Age"].mode() # Find most Common Value.
df["Age"].std() # Shows how spread out the values are.

np.float64(0.8944271909999159)

In [83]:
# Checking Data Quality
df.duplicated().sum()
df[df.duplicated()]

Empty DataFrame
Columns: [Name, Age, Department]
Index: []